### ISSUE TITLE
随机崩溃，附日志，谢谢。

### ISSUE THREAD

**Issue by vivikuyo** [xjn819/Hackintosh-Deskmini310-EFI#10]
大佬求救，8600k，情况是单显示器使用正常，但是只要接双显示器，可以正常使用一段时间，然后必然莫名其妙崩溃重启，求大佬指点。。

panic(cpu 4 caller 0xffffff8009fee1e6): Kernel trap at 0xffffff8009f76555, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff87c0000018, CR3: 0x000000045b68404b, CR4: 0x00000000003626e0
RAX: 0x0000000021000000, RBX: 0x0000000000000000, RCX: 0xffffff87c0000000, RDX: 0xffffff7f80000000
RSP: 0xffffffa07b77b8f0, RBP: 0xffffffa07b77b930, RSI: 0x0000000000000000, RDI: 0xffffff803ae8bc00
R8: 0xffffffa07b77b9a4, R9: 0xffffff8039324be0, R10: 0x0000000000000001, R11: 0xffffff9379c0b5b4
R12: 0xffffff803ae8bc00, R13: 0x0000000000020000, R14: 0x0000000000000001, R15: 0xffffff87c0000000
RFL: 0x0000000000010287, RIP: 0xffffff8009f76555, CS: 0x0000000000000008, SS: 0x0000000000000010
Fault CR2: 0xffffff87c0000018, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffffa07b77b310 : 0xffffff8009ebab4d
0xffffffa07b77b360 : 0xffffff8009ffd7e3
0xffffffa07b77b3a0 : 0xffffff8009fede1a
0xffffffa07b77b3f0 : 0xffffff8009e5fa2f
0xffffffa07b77b410 : 0xffffff8009eba3ed
0xffffffa07b77b530 : 0xffffff8009eba6d8
0xffffffa07b77b5a0 : 0xffffff800a6bef9a
0xffffffa07b77b610 : 0xffffff8009fee1e6
0xffffffa07b77b790 : 0xffffff8009fedecd
0xffffffa07b77b7e0 : 0xffffff8009e5fa2f
0xffffffa07b77b800 : 0xffffff8009f76555
0xffffffa07b77b930 : 0xffffff8009fa1d35
0xffffffa07b77b970 : 0xffffff800a62feb1
0xffffffa07b77b9d0 : 0xffffff7faa50d762
0xffffffa07b77ba20 : 0xffffff7faa54c9f4
0xffffffa07b77ba90 : 0xffffff7faa55bc34
0xffffffa07b77bad0 : 0xffffff800a64628e
0xffffffa07b77bb20 : 0xffffff800a65045b
0xffffffa07b77bc80 : 0xffffff8009fa8e51
0xffffffa07b77bd90 : 0xffffff8009ec0147
0xffffffa07b77be00 : 0xffffff8009e96905
0xffffffa07b77be60 : 0xffffff8009eae062
0xffffffa07b77bef0 : 0xffffff8009fd1fc3
0xffffffa07b77bfa0 : 0xffffff8009e60216
Kernel Extensions in backtrace:
com.apple.iokit.IOAcceleratorFamily2(439.52)[7B467C8D-2528-3663-8024-B09E1DCED75A]@0xffffff7faa50b000->0xffffff7faa574fff
dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2A454117-CDAA-301F-B609-BA396742C91A]@0xffffff800b401000->0xffffff800b415fff
dependency: com.apple.iokit.IOGraphicsFamily(585)[EF8876FC-C6D6-3D53-9915-762EF4F12870]@0xffffff7faa663000->0xffffff7faa691fff
dependency: com.apple.iokit.IOPCIFamily(2.9)[BF2C5E86-1E8F-3FD4-9874-7738178FA73B]@0xffffff800c81f000->0xffffff800c846fff
dependency: com.apple.iokit.IOReportFamily(47)[D3C4FAA4-8F06-3C5C-AB36-4BE632CCE051]@0xffffff800c855000->0xffffff800c857fff
dependency: com.apple.iokit.IOSurface(289.3)[22DEF369-CE8F-3ACF-BD1E-4CE16AAB209A]@0xffffff800c966000->0xffffff800c981fff

Process name corresponding to current thread: systemstats
Boot args: igfxfw=2 igfxonln=1

Mac OS version:
20D91

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000009c00000
KernelCache base: 0xffffff8009e00000
Kernel slide: 0x0000000009c10000
Kernel text base: 0xffffff8009e10000
__HIB text base: 0xffffff8009d00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4216986258157
Last Sleep: absolute base_tsc base_nano
Uptime : 0x000003d5d7f7cd98
Sleep : 0x0000000000000000 0x0000000000000000 0x0000000000000000
Wake : 0x0000000000000000 0x00000014e4de6ba0 0x0000000000000000

**Comment by vivikuyo** [comment]
panic(cpu 4 caller 0xffffff8009fee1e6): Kernel trap at 0xffffff8009f76555, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff87c0000018, CR3: 0x000000045b68404b, CR4: 0x00000000003626e0
RAX: 0x0000000021000000, RBX: 0x0000000000000000, RCX: 0xffffff87c0000000, RDX: 0xffffff7f80000000
RSP: 0xffffffa07b77b8f0, RBP: 0xffffffa07b77b930, RSI: 0x0000000000000000, RDI: 0xffffff803ae8bc00
R8:  0xffffffa07b77b9a4, R9:  0xffffff8039324be0, R10: 0x0000000000000001, R11: 0xffffff9379c0b5b4
R12: 0xffffff803ae8bc00, R13: 0x0000000000020000, R14: 0x0000000000000001, R15: 0xffffff87c0000000
RFL: 0x0000000000010287, RIP: 0xffffff8009f76555, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff87c0000018, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffffa07b77b310 : 0xffffff8009ebab4d 
0xffffffa07b77b360 : 0xffffff8009ffd7e3 
0xffffffa07b77b3a0 : 0xffffff8009fede1a 
0xffffffa07b77b3f0 : 0xffffff8009e5fa2f 
0xffffffa07b77b410 : 0xffffff8009eba3ed 
0xffffffa07b77b530 : 0xffffff8009eba6d8 
0xffffffa07b77b5a0 : 0xffffff800a6bef9a 
0xffffffa07b77b610 : 0xffffff8009fee1e6 
0xffffffa07b77b790 : 0xffffff8009fedecd 
0xffffffa07b77b7e0 : 0xffffff8009e5fa2f 
0xffffffa07b77b800 : 0xffffff8009f76555 
0xffffffa07b77b930 : 0xffffff8009fa1d35 
0xffffffa07b77b970 : 0xffffff800a62feb1 
0xffffffa07b77b9d0 : 0xffffff7faa50d762 
0xffffffa07b77ba20 : 0xffffff7faa54c9f4 
0xffffffa07b77ba90 : 0xffffff7faa55bc34 
0xffffffa07b77bad0 : 0xffffff800a64628e 
0xffffffa07b77bb20 : 0xffffff800a65045b 
0xffffffa07b77bc80 : 0xffffff8009fa8e51 
0xffffffa07b77bd90 : 0xffffff8009ec0147 
0xffffffa07b77be00 : 0xffffff8009e96905 
0xffffffa07b77be60 : 0xffffff8009eae062 
0xffffffa07b77bef0 : 0xffffff8009fd1fc3 
0xffffffa07b77bfa0 : 0xffffff8009e60216 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(439.52)[7B467C8D-2528-3663-8024-B09E1DCED75A]@0xffffff7faa50b000->0xffffff7faa574fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2A454117-CDAA-301F-B609-BA396742C91A]@0xffffff800b401000->0xffffff800b415fff
            dependency: com.apple.iokit.IOGraphicsFamily(585)[EF8876FC-C6D6-3D53-9915-762EF4F12870]@0xffffff7faa663000->0xffffff7faa691fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[BF2C5E86-1E8F-3FD4-9874-7738178FA73B]@0xffffff800c81f000->0xffffff800c846fff
            dependency: com.apple.iokit.IOReportFamily(47)[D3C4FAA4-8F06-3C5C-AB36-4BE632CCE051]@0xffffff800c855000->0xffffff800c857fff
            dependency: com.apple.iokit.IOSurface(289.3)[22DEF369-CE8F-3ACF-BD1E-4CE16AAB209A]@0xffffff800c966000->0xffffff800c981fff

Process name corresponding to current thread: systemstats
Boot args: igfxfw=2 igfxonln=1 

Mac OS version:
20D91

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000009c00000
KernelCache base:  0xffffff8009e00000
Kernel slide:      0x0000000009c10000
Kernel text base:  0xffffff8009e10000
__HIB  text base: 0xffffff8009d00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4216986258157
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000003d5d7f7cd98
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000014e4de6ba0 0x0000000000000000

**Comment by vivikuyo** [comment]
panic(cpu 0 caller 0xffffff8007bee1e6): Kernel trap at 0xffffff8008014a35, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff770adde663, CR3: 0x000000025e0d4049, CR4: 0x00000000003626e0
RAX: 0xffffff770adde6e0, RBX: 0x0000000000000000, RCX: 0x00ffffff86ac18a0, RDX: 0x0000000f86ac18a0
RSP: 0xffffffa05c48b6f0, RBP: 0xffffffa05c48b710, RSI: 0xffffffa05c48b730, RDI: 0xffffff86ac18a000
R8:  0xffffffa05c48b8e0, R9:  0xffffffff00000000, R10: 0xffffff7fa8136afc, R11: 0xffffff936b503db4
R12: 0x0000000000000000, R13: 0xffffff86ab140650, R14: 0xffffff86bf030930, R15: 0xffffff800832808c
RFL: 0x0000000000010246, RIP: 0xffffff8008014a35, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff770adde663, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffffa05c48b110 : 0xffffff8007abab4d 
0xffffffa05c48b160 : 0xffffff8007bfd7e3 
0xffffffa05c48b1a0 : 0xffffff8007bede1a 
0xffffffa05c48b1f0 : 0xffffff8007a5fa2f 
0xffffffa05c48b210 : 0xffffff8007aba3ed 
0xffffffa05c48b330 : 0xffffff8007aba6d8 
0xffffffa05c48b3a0 : 0xffffff80082bef9a 
0xffffffa05c48b410 : 0xffffff8007bee1e6 
0xffffffa05c48b590 : 0xffffff8007bedecd 
0xffffffa05c48b5e0 : 0xffffff8007a5fa2f 
0xffffffa05c48b600 : 0xffffff8008014a35 
0xffffffa05c48b710 : 0xffffff800824a5d3 
0xffffffa05c48b740 : 0xffffff800826e572 
0xffffffa05c48b770 : 0xffffff8007ba1b30 
0xffffffa05c48b7b0 : 0xffffff800822fb26 
0xffffffa05c48b800 : 0xffffff7fa8160ec1 
0xffffffa05c48b8d0 : 0xffffff7fa815de80 
0xffffffa05c48b930 : 0xffffff7fa812c1c7 
0xffffffa05c48b960 : 0xffffff7fa812c4d7 
0xffffffa05c48b990 : 0xffffff7fa8136b9e 
0xffffffa05c48b9d0 : 0xffffff8008247c71 
0xffffffa05c48ba80 : 0xffffff800824632a 
0xffffffa05c48bad0 : 0xffffff7fa8138272 
0xffffffa05c48bb20 : 0xffffff800825045b 
0xffffffa05c48bc80 : 0xffffff8007ba8e51 
0xffffffa05c48bd90 : 0xffffff8007ac0147 
0xffffffa05c48be00 : 0xffffff8007a96905 
0xffffffa05c48be60 : 0xffffff8007aae062 
0xffffffa05c48bef0 : 0xffffff8007bd1fc3 
0xffffffa05c48bfa0 : 0xffffff8007a60216 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(439.52)[7B467C8D-2528-3663-8024-B09E1DCED75A]@0xffffff7fa810b000->0xffffff7fa8174fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2A454117-CDAA-301F-B609-BA396742C91A]@0xffffff8009001000->0xffffff8009015fff
            dependency: com.apple.iokit.IOGraphicsFamily(585)[EF8876FC-C6D6-3D53-9915-762EF4F12870]@0xffffff7fa8263000->0xffffff7fa8291fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[BF2C5E86-1E8F-3FD4-9874-7738178FA73B]@0xffffff800a41f000->0xffffff800a446fff
            dependency: com.apple.iokit.IOReportFamily(47)[D3C4FAA4-8F06-3C5C-AB36-4BE632CCE051]@0xffffff800a455000->0xffffff800a457fff
            dependency: com.apple.iokit.IOSurface(289.3)[22DEF369-CE8F-3ACF-BD1E-4CE16AAB209A]@0xffffff800a566000->0xffffff800a581fff

Process name corresponding to current thread: WindowServer
Boot args: igfxfw=2 igfxonln=1 

Mac OS version:
20D91

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000007800000
KernelCache base:  0xffffff8007a00000
Kernel slide:      0x0000000007810000
Kernel text base:  0xffffff8007a10000
__HIB  text base: 0xffffff8007900000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 870512413303
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000caae954e18
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000013ef527a12 0x0000000000000000

**Comment by xjn819** [comment]
硬件问题

**Comment by nabaonan** [comment]
我也是遇到过类似的状况，接俩显示器，睡眠唤醒后莫名系统崩溃，然后显示器的dp怎么接都没信号了
