### ISSUE TITLE
什么时候支持升级oc0.7.2？

### ISSUE THREAD

**Issue by nabaonan** [xjn819/Hackintosh-Deskmini310-EFI#12]

**Comment by xjn819** [comment]
除非Monterey发布，不然不会更新，目前的efi已经支持mojave-big sur的所有正式版

**Comment by nabaonan** [comment]
> 除非Monterey发布，不然不会更新，目前的efi已经支持mojave-big sur的所有正式版

好的，这个efi是通用的版本？我现在没有升级到最新的bigsur还是在catalina，也可以的吧？
