### ISSUE TITLE
休眠唤醒之后，可以正常登录，可是没办法登出

### ISSUE THREAD

**Issue by xingqiri** [xjn819/Hackintosh-Deskmini310-EFI#14]
不知道各位大佬有没有碰到过这种情况，睡眠唤醒正常，可以登录，但是再登出就会一直卡住，只能长按电源键强制关机。

**Comment by xingqiri** [comment]
我把系统升级到11.6.1碰到的这个问题。刚刚我把所有的kext文件都更新到最新版本，这个问题就解决了，应该是iGPU的问题。休眠唤醒之后所有需要显卡加速的App全部卡死，驱动更新到最新搞定。

**Comment by ROCKBUND** [comment]
我这边直接升到11.6.1无限重启，大佬怎么升的
