### ISSUE TITLE
拆机卡（BCM943602CS）+转接卡问题

### ISSUE THREAD

**Issue by yjkddlt** [xjn819/Hackintosh-Deskmini310-EFI#15]
大佬好，请问你的（BCM943602CS）+转接卡装上后，nvme硬盘有办法固定吗？
我装上后，转接卡凸出了，nvme没法固定

**Comment by xiaooloong** [comment]
我就是 2cs + 转接卡，nvme 盘只要是单面颗粒的盘就不会翘得特别厉害，可以给 nvme 的螺丝下面垫个一、两毫米的垫片，别让 nvme 硬盘吃应力就可以了。

**Comment by yjkddlt** [comment]
谢谢，我换成bcm94360cs2了。bcm94360cs2居然和bcm943602cs厚度不一样，前者基本可以完美固定nvme硬盘。
