### ISSUE TITLE
大佬还有空更新一下适配12.3的系统吗？

### ISSUE THREAD

**Issue by mrxiaozuo** [xjn819/Hackintosh-Deskmini310-EFI#17]

**Comment by yjkddlt** [comment]
这个efi可以用12.3，我直接升级了，连接dp的话，需要加一个启动参数gfxagdc=0

**Comment by mrxiaozuo** [comment]
> 

还有其他问题吗？

**Comment by mrxiaozuo** [comment]
> 这个efi可以用12.3，我直接升级了，连接dp的话，需要加一个启动参数gfxagdc=0

还有其他问题吗？

**Comment by yjkddlt** [comment]
dp 偶尔会黑屏，比如锁屏一段时间后，dp唤不醒；

**Comment by yjkddlt** [comment]
> dp 偶尔会黑屏，比如锁屏一段时间后，dp唤不醒；

12.3.1好像已经修复了这个问题。

**Comment by mrxiaozuo** [comment]
> > dp 偶尔会黑屏，比如锁屏一段时间后，dp唤不醒；
> 
> 12.3.1好像已经修复了这个问题。

自己动手升级到了oc079问题不大

**Comment by xjn819** [comment]
最近太忙了，清明假期搞一下
