### ISSUE TITLE
大佬 我使用最新的efi 升级bigsur 出现了一些问题

### ISSUE THREAD

**Issue by jc840031139** [xjn819/Hackintosh-Deskmini310-EFI#6]
开机时间巨长 可能是网卡引起的  开机后蓝牙不可用 之前在10.15.7一切正常

**Comment by jc840031139** [comment]
问题已经解决 dw1820a的驱动 BrcmPatchRAM2.kext 升级bigsur要更新到BrcmPatchRAM3.kext

**Comment by ghost** [comment]
> 问题已经解决 dw1820a的驱动 BrcmPatchRAM2.kext 升级bigsur要更新到BrcmPatchRAM3.kext

@jc840031139 请问, 升级到Big Sur并更新驱动到BrcmPatchRAM3.kext. Wi-Fi和蓝牙使用正常吗

**Comment by xjn819** [comment]
会在下次更新中修复 谢谢

**Comment by xjn819** [comment]
fixed
